# Generated by Django 5.1.7 on 2025-04-10 20:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(choices=[('Frutos secos', 'Frutos secos'), ('Semillas', 'Semillas'), ('Deshidratado', 'Deshidratado'), ('Cereales', 'Cereales'), ('Mixes', 'Mixes'), ('Huevos', 'Huevos'), ('Encurtidos', 'Encurtidos'), ('Chocolates', 'Chocolates')], max_length=255, unique=True)),
            ],
            options={
                'db_table': 'categorias',
            },
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('descripcion', models.CharField(max_length=255)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=20)),
                ('stock', models.DecimalField(decimal_places=2, max_digits=20)),
                ('urlfoto', models.URLField(blank=True, null=True)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventario.categoria')),
            ],
            options={
                'db_table': 'productos',
            },
        ),
    ]
