# Generated by Django 5.1.7 on 2025-04-07 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('descripcion', models.CharField(max_length=255)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=20)),
                ('stock', models.DecimalField(decimal_places=2, max_digits=20)),
                ('categoria', models.CharField(max_length=255)),
                ('urlfoto', models.URLField(blank=True, null=True)),
            ],
            options={
                'db_table': 'productos',
            },
        ),
    ]
