# Generated by Django 5.1.7 on 2025-04-07 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0004_alter_producto_categoria'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoria',
            name='nombre',
            field=models.CharField(choices=[('Frutos secos', 'Frutos secos'), ('Semillas', 'Semillas'), ('Deshidratado', 'Deshidratado'), ('Cereales', 'Cereales'), ('Mixes', 'Mixes'), ('Huevos', 'Huevos'), ('Encurtidos', 'Encurtidos'), ('Chocolates', 'Chocolates')], max_length=255, unique=True),
        ),
    ]
